package co.edu.usbcali.breakfast.modelo;
// Generated 31/05/2016 10:38:31 AM by Hibernate Tools 4.3.1.Final



/**
 * Pedidoproducto generated by hbm2java
 */
public class Pedidoproducto  implements java.io.Serializable {


     private Long codigoPedidoProducto;
     private Pedido pedido;
     private Producto producto;
     private Long codigoUsuario;
     private Long codigoTipoproducto;

    public Pedidoproducto() {
    }

    public Pedidoproducto(Long codigoPedidoProducto, Pedido pedido, Producto producto, Long codigoUsuario, Long codigoTipoproducto) {
       this.codigoPedidoProducto = codigoPedidoProducto;
       this.pedido = pedido;
       this.producto = producto;
       this.codigoUsuario = codigoUsuario;
       this.codigoTipoproducto = codigoTipoproducto;
    }
   
    public Long getCodigoPedidoProducto() {
        return this.codigoPedidoProducto;
    }
    
    public void setCodigoPedidoProducto(Long codigoPedidoProducto) {
        this.codigoPedidoProducto = codigoPedidoProducto;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Long getCodigoUsuario() {
        return this.codigoUsuario;
    }
    
    public void setCodigoUsuario(Long codigoUsuario) {
        this.codigoUsuario = codigoUsuario;
    }
    public Long getCodigoTipoproducto() {
        return this.codigoTipoproducto;
    }
    
    public void setCodigoTipoproducto(Long codigoTipoproducto) {
        this.codigoTipoproducto = codigoTipoproducto;
    }




}


