package co.edu.usbcali.breakfast.modelo;
// Generated 31/05/2016 10:38:31 AM by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Long codigoPedido;
     private Usuario usuario;
     private Date fecha;
     private Set<Pedidoproducto> pedidoproductos = new HashSet<Pedidoproducto>(0);

    public Pedido() {
    }

	
    public Pedido(Long codigoPedido, Usuario usuario, Date fecha) {
        this.codigoPedido = codigoPedido;
        this.usuario = usuario;
        this.fecha = fecha;
    }
    public Pedido(Long codigoPedido, Usuario usuario, Date fecha, Set<Pedidoproducto> pedidoproductos) {
       this.codigoPedido = codigoPedido;
       this.usuario = usuario;
       this.fecha = fecha;
       this.pedidoproductos = pedidoproductos;
    }
   
    public Long getCodigoPedido() {
        return this.codigoPedido;
    }
    
    public void setCodigoPedido(Long codigoPedido) {
        this.codigoPedido = codigoPedido;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set<Pedidoproducto> getPedidoproductos() {
        return this.pedidoproductos;
    }
    
    public void setPedidoproductos(Set<Pedidoproducto> pedidoproductos) {
        this.pedidoproductos = pedidoproductos;
    }




}


