package co.edu.usbcali.breakfast.modelo;
// Generated 31/05/2016 10:38:31 AM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Long codigoProducto;
     private Tipoproducto tipoproducto;
     private String nombre;
     private Long descripcion;
     private Long precio;
     private String imagen;
     private Set<Pedidoproducto> pedidoproductos = new HashSet<Pedidoproducto>(0);

    public Producto() {
    }

	
    public Producto(Long codigoProducto, Tipoproducto tipoproducto, String nombre, Long descripcion, Long precio) {
        this.codigoProducto = codigoProducto;
        this.tipoproducto = tipoproducto;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.precio = precio;
    }
    public Producto(Long codigoProducto, Tipoproducto tipoproducto, String nombre, Long descripcion, Long precio, String imagen, Set<Pedidoproducto> pedidoproductos) {
       this.codigoProducto = codigoProducto;
       this.tipoproducto = tipoproducto;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precio = precio;
       this.imagen = imagen;
       this.pedidoproductos = pedidoproductos;
    }
   
    public Long getCodigoProducto() {
        return this.codigoProducto;
    }
    
    public void setCodigoProducto(Long codigoProducto) {
        this.codigoProducto = codigoProducto;
    }
    public Tipoproducto getTipoproducto() {
        return this.tipoproducto;
    }
    
    public void setTipoproducto(Tipoproducto tipoproducto) {
        this.tipoproducto = tipoproducto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Long getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(Long descripcion) {
        this.descripcion = descripcion;
    }
    public Long getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Long precio) {
        this.precio = precio;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public Set<Pedidoproducto> getPedidoproductos() {
        return this.pedidoproductos;
    }
    
    public void setPedidoproductos(Set<Pedidoproducto> pedidoproductos) {
        this.pedidoproductos = pedidoproductos;
    }




}


